/// Flutter icons Tfticons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tfticons
///      fonts:
///       - asset: fonts/Tfticons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Tfticons {
  Tfticons._();

  static const _kFontFam = 'Tfticons';
  static const String _kFontPkg = null;

  static const IconData adept = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assassin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brawler = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultist = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dazzler = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData divine = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duelist = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dusk = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elderwood = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emperor = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enlightened = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exile = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fortune = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hunter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keeper = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mage = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moonlight = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mystic = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ninja = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shade = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sharpshooter = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spirit = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theboss = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tormented = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vanguard = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warlord = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
